version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: soporte_postgres
    restart: always
    environment:
      POSTGRES_DB: soporte_db
      POSTGRES_USER: soporte_user
      POSTGRES_PASSWORD: soporte_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soporte_app
    depends_on:
      - postgres
    ports:
      - "8181:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/soporte_db
      SPRING_DATASOURCE_USERNAME: soporte_user
      SPRING_DATASOURCE_PASSWORD: soporte_pass

volumes:
  postgres-data:
